version: '2'
services:
    jobit-app:
        image: jobit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jobit-mysql:3306/jobit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jobit-mysql:
        extends:
            file: mysql.yml
            service: jobit-mysql
